name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.js
        with:
          who-to-greet: 'Albin'
      - name: Log Greeting timestamp
        run: echo "${{ steps.greet.outputs.time }}"